server:
  port: 8081

spring:
  application:
    name: player_two

game:
  second-player:
    play-url: http://localhost:8080/threegame/play
    start-url: http://localhost:8080/threegame/start-game
  random-number-min: 10
  random-number-max: 1000
